// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCMmWy8AUSv7KwDFhu05Y_LXfbpWjo3cQ',
    appId: '1:653739013774:android:c22be8e794309290103bdf',
    messagingSenderId: '653739013774',
    projectId: 'flutter-calorie-calculator',
    storageBucket: 'flutter-calorie-calculator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHVcNxuY-oCZT07wa1hSke3rxti7FcTiU',
    appId: '1:653739013774:ios:33974b2ba72c2be2103bdf',
    messagingSenderId: '653739013774',
    projectId: 'flutter-calorie-calculator',
    storageBucket: 'flutter-calorie-calculator.firebasestorage.app',
    iosClientId: '653739013774-s2bp1he54m05tv0a55vc2vv8jig3f48k.apps.googleusercontent.com',
    iosBundleId: 'com.vinsonguo.flutteriptvclient.flutterIptvClient',
  );

}